# Name of your application. Used to uniquely configure containers.
service: whatsapp-group-frontend

# Name of the container image.
image: willywg/whatsapp-group-frontend

# Deploy to these servers.
servers:
  web:
    hosts:
      - 179.43.114.242

registry:
  username: willywg
  password:
    - DOCKER_REGISTRY_PASSWORD

# Inject ENV variables into containers (secrets come from .env).
# Remember to run `kamal env push` after making changes!
env:
  clear:
    NODE_ENV: production
    PORT: 3000
  secret:
    - VITE_API_BASE_URL
    - VITE_WEBSOCKET_URL

ssh:
  user: william
  port: 2219

builder:
  arch: x86_64

proxy:
  ssl: true
  host: "wsf.arguita.com.ar"
  app_port: 3000

aliases:
  apps: server exec docker exec kamal-proxy kamal-proxy list
  stats: server exec "docker stats --no-stream"
  stats-live: server exec -i "docker stats"
  ps: server exec "docker ps"
  htop: server exec -i "htop"
  server-terminal: server exec -i "bash"
  app-terminal: app exec -i "bash"